payroll/urls.py
from django.conf.urls import url, include
from .views import *

urlpatterns = [
    url(r'^list', PayrollListView.as_view(), name='list'),
    url(r'^(?P<pk>[0-9]+)/$', PayrollDetailView.as_view(), name='detail'),
    url(r'^entry/$', PayrollEntryView.as_view(), name='entry'),
    url(r'^(?P<pk>[0-9]+)/review/$', PayrollReviewView.as_view(), name='review'),
]

profiles/urls.py
from django.conf.urls import url, include
from .views import ProfileCreateView

urlpatterns = [
    url(r'^signup', ProfileCreateView.as_view(), name='signup'),
]

sebastien/urls.py
from django.conf.urls import url, include
from django.urls import reverse_lazy
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='__base.html'), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^payroll/', include(('payroll.urls', 'payroll'), namespace='payroll')),
    url(r'^payroll/$',RedirectView.as_view(url=reverse_lazy('payroll:list')), name='payroll_redirect'),
    url(r'^accounts/', include(('profiles.urls', 'profiles'), namespace='profile')),
    url(r'^accounts/login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^accounts/logout/$', auth_views.logout, {'next_page': 'home'}, name='logout'),
]

payroll/models.py
import datetime

from django.db import models
from django.db.models import Sum, F

from profiles.models import Profile

# Create your models here.
class Payroll(models.Model):
    employee = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=True, related_name='employee_paystubs')
    current_wage = models.DecimalField(blank=True, max_digits=6, decimal_places=2)
    pay_period_start = models.DateField()
    pay_period_end = models.DateField()
    hours = models.DecimalField(max_digits=6, decimal_places=2)
    date_paid = models.DateField(blank=True, null=True)
    paid = models.BooleanField(default=False)
    # the following taxes are calculated on save
    employee_medicare = models.DecimalField(blank=True, max_digits=6, decimal_places=2)
    employee_social_security = models.DecimalField(blank=True, max_digits=6, decimal_places=2)
    employer_medicare = models.DecimalField(blank=True, max_digits=6, decimal_places=2)
    employer_social_security = models.DecimalField(blank=True, max_digits=6, decimal_places=2)
    futa = models.DecimalField(blank=True, max_digits=6, decimal_places=2)
    wa_uta = models.DecimalField(blank=True, max_digits=6, decimal_places=2)
    gross_total = models.DecimalField(blank=True, max_digits=6, decimal_places=2)

    def save(self, *args, **kwargs):
        # Calculate whether FUTA should be withheld and, if so, how much.
        # FUTA is only withheld on the first $7,000 in wages.
        self.current_wage = self.employee.wage
        current_year = datetime.datetime.now().year
        if Payroll.objects.filter(employee=self.employee):
            current_year_payroll_hours = Payroll.objects.filter(employee=self.employee).exclude(
                pay_period_end__year__lt=current_year, pay_period_end__year__gt=current_year).aggregate(
                Sum('hours'))
            if current_year_payroll_hours['hours__sum'] * self.current_wage < 7000:
                self.futa = float((self.hours * self.current_wage)) * .006
            else:
                self.futa = 0
        else:
            self.futa = float((self.hours * self.current_wage)) * .006
        # Calculate other taxes.
        self.employee_medicare = self.employer_medicare = float((self.hours * self.current_wage)) * .0145
        self.employee_social_security = self.employer_social_security = float((self.hours * self.current_wage)) * .062
        self.wa_uta = float((self.hours * self.current_wage)) * .0119
        self.gross_total = float((self.hours * self.current_wage))
        return super(Payroll, self).save(*args, **kwargs)

    class Meta:
        ordering = ('-pay_period_start',)
        permissions = (
            ('approve_payroll', 'Approve Payroll'),
        )

    def __str__(self):
        return "{0} to {1}".format(self.pay_period_start.strftime('%m/%d/%Y'), self.pay_period_end.strftime('%m/%d/%Y'))

templates/__base.html
{% block doctype %}<!DOCTYPE html>{% endblock %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>
        {% block title %}
            Sébastien's Page.
        {% endblock %}
        </title>

        {% block css %}
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.css">
        {% endblock %}

        {% block scripts %}
            <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.js"></script>
        {% endblock %}

    </head>

    <body>

    {% block navbar %}
        {% include '__navbar.html' %}
    {% endblock %}

        <div class="row justify-content-center">
            {% include '__messages.html' %}
        </div>
    <div class="container-fluid d-flex justify-content-between pt-2">
            <div class="p-0 col-md-2">
                {% block left_sidebar %}
                {% endblock %}
            </div>

            <div class="p-0 col-md-7">
                {% block center_bar %}
                {% endblock %}
            </div>

            <div class="p-0 col-md-2">
                {% block right_sidebar %}
                {% endblock %}
            </div>

    </div>

    </body>
</html>

templates/__messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}

templates/__navbar.html
{% load profile_extras %}
<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'home' %}">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
          {% if perms.payroll.add_payroll or perms.payroll.approve_payroll %}
              <a class="nav-link" href="{% url 'payroll:list' %}">Payroll <span class="sr-only">(current)</span></a>
          {% endif %}
      </li>
    </ul>
      {% if not user.is_authenticated %}
          <div class="button-group">
            <a href="{% url 'profile:signup' %}"><button class="btn btn-primary" type="button">Signup</button></a>
            <a href="{% url 'login' %}"><button class="btn btn-primary" type="button">Login</button></a>
          </div>
      {% else %}
          <div class="button-group">
            <a href="{% url 'logout' %}"><button class="btn btn-danger" type="button">Logout</button></a>
          </div>
      {% endif %}

  </div>
</nav>

templates/login.html
{% extends './__base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Login to Sébastien's Page
{% endblock %}

{% block center_bar %}
    <div class="card">
        <div class="card-header">
            <h4>Login</h4>
        </div>
        <div class="card-body">
            <form action="{% url 'login' %}" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="hidden" name="next" value="{{ next }}">
                <button class="btn btn-primary" type="submit" value="Login">Login</button>
            </form>
        </div>
    </div>
{% endblock %}