payroll/urls.py
from django.conf.urls import url, include
from .views import *

urlpatterns = [
    url(r'^list', PayrollListView.as_view(), name='list'),
    url(r'^(?P<pk>[0-9]+)/$', PayrollDetailView.as_view(), name='detail'),
    url(r'^entry/$', PayrollEntryView.as_view(), name='entry'),
    url(r'^(?P<pk>[0-9]+)/review/$', PayrollReviewView.as_view(), name='review'),
]

sebastien/urls.py
from django.conf.urls import url, include
from django.urls import reverse_lazy
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='__base.html'), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^payroll/', include(('payroll.urls', 'payroll'), namespace='payroll')),
    url(r'^payroll/$',RedirectView.as_view(url=reverse_lazy('payroll:list')), name='payroll_redirect'),
    url(r'^accounts/', include(('profiles.urls', 'profiles'), namespace='profile')),
    url(r'^accounts/login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^accounts/logout/$', auth_views.logout, {'next_page': 'home'}, name='logout'),
]

payroll/models.py
import datetime

from django.db import models
from django.db.models import Sum, F

from profiles.models import Profile

# Create your models here.
class Payroll(models.Model):
    employee = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=True, related_name='employee_paystubs')
    current_wage = models.DecimalField(blank=True, max_digits=6, decimal_places=2)
    pay_period_start = models.DateField()
    pay_period_end = models.DateField()
    hours = models.DecimalField(max_digits=6, decimal_places=2)
    date_paid = models.DateField(blank=True, null=True)
    paid = models.BooleanField(default=False)
    # the following taxes are calculated on save
    employee_medicare = models.DecimalField(blank=True, max_digits=6, decimal_places=2)
    employee_social_security = models.DecimalField(blank=True, max_digits=6, decimal_places=2)
    employer_medicare = models.DecimalField(blank=True, max_digits=6, decimal_places=2)
    employer_social_security = models.DecimalField(blank=True, max_digits=6, decimal_places=2)
    futa = models.DecimalField(blank=True, max_digits=6, decimal_places=2)
    wa_uta = models.DecimalField(blank=True, max_digits=6, decimal_places=2)
    gross_total = models.DecimalField(blank=True, max_digits=6, decimal_places=2)

    def save(self, *args, **kwargs):
        # Calculate whether FUTA should be withheld and, if so, how much.
        # FUTA is only withheld on the first $7,000 in wages.
        self.current_wage = self.employee.wage
        current_year = datetime.datetime.now().year
        if Payroll.objects.filter(employee=self.employee):
            current_year_payroll_hours = Payroll.objects.filter(employee=self.employee).exclude(
                pay_period_end__year__lt=current_year, pay_period_end__year__gt=current_year).aggregate(
                Sum('hours'))
            if current_year_payroll_hours['hours__sum'] * self.current_wage < 7000:
                self.futa = float((self.hours * self.current_wage)) * .006
            else:
                self.futa = 0
        else:
            self.futa = float((self.hours * self.current_wage)) * .006
        # Calculate other taxes.
        self.employee_medicare = self.employer_medicare = float((self.hours * self.current_wage)) * .0145
        self.employee_social_security = self.employer_social_security = float((self.hours * self.current_wage)) * .062
        self.wa_uta = float((self.hours * self.current_wage)) * .0119
        self.gross_total = float((self.hours * self.current_wage))
        return super(Payroll, self).save(*args, **kwargs)

    class Meta:
        ordering = ('-pay_period_start',)
        permissions = (
            ('approve_payroll', 'Approve Payroll'),
        )

    def __str__(self):
        return "{0} to {1}".format(self.pay_period_start.strftime('%m/%d/%Y'), self.pay_period_end.strftime('%m/%d/%Y'))

payroll/forms.py
from django import forms
from django.forms import ModelForm

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Fieldset, Button, Field, Div
from crispy_forms.bootstrap import FormActions, AppendedText

from payroll.models import Payroll
from profiles.models import Profile



class Row(Div):
    css_class = "form-row"


class PayrollEntryForm(ModelForm):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(PayrollEntryForm, self).__init__(*args, **kwargs)
        self.fields['employee'].queryset = Profile.objects.filter(wage__isnull=False).prefetch_related('user')
        self.helper = FormHelper(self)
        self.helper.form_id = 'id-PayrollForm'
        self.helper.form_method = 'post'
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-8'
        self.helper.layout = Layout(
            Field('employee'),
            Field('pay_period_start', autocomplete='off'),
            Field('pay_period_end', autocomplete='off'),
            'hours',
            FormActions(
                Submit('save', 'Save', css_class='btn-primary'),
                Submit('cancel', 'Cancel', css_class='btn btn-danger', formnovalidate='formnovalidate'),
            )
        )
        if self.user.groups.filter(name='Nanny').exists():
            del self.fields['employee']

    def clean(self):
        cleaned_data = super(PayrollEntryForm, self).clean()
        start_date = cleaned_data.get('pay_period_start')
        end_date = cleaned_data.get('pay_period_end')
        if end_date < start_date:
            msg = 'Pay period end date must be after pay period start date.'
            self._errors['pay_period_end'] = self.error_class([msg])

    class Meta:
        model = Payroll
        fields = ['employee', 'pay_period_start', 'pay_period_end', 'hours']


class PayrollReviewForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(PayrollReviewForm, self).__init__(*args, **kwargs)

        self.fields['employee'].queryset = Profile.objects.filter(wage__isnull=False).prefetch_related('user')

        self.helper = FormHelper(self)
        self.helper.form_method = 'post'
        self.helper.layout = Layout(
            Row(
                Field('employee', wrapper_class='col-md-8'),
            ),
            Row(
                Field('pay_period_start', wrapper_class='col-md-4', autocomplete='off'),
                Field('pay_period_end', wrapper_class='col-md-4', autocomplete='off'),
                Field('hours', wrapper_class='col-md-4'),
            ),
        )
        self.helper.add_input(Submit('submit', 'Paid', css_class='btn-default'))
        self.helper.add_input(Submit('cancel', 'Cancel', css_class='btn-danger', formnovalidate='formnovalidate'))

    class Meta:
        model = Payroll
        fields = ['employee', 'pay_period_start', 'pay_period_end', 'hours']

payroll/views.py
import datetime

from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import HttpResponseRedirect, Http404
from django.db.models import Sum, F
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.core.mail import send_mail
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist

from braces import views

from .forms import PayrollEntryForm, PayrollReviewForm
from .models import Payroll


# Create your views here.
class PayrollListView(views.LoginRequiredMixin,
                      views.MultiplePermissionsRequiredMixin,
                      ListView):
    permissions = {
        'any': ('payroll.add_payroll', 'payroll.approve_payroll')
    }
    model = Payroll
    template_name = 'payroll/payroll_list.html'

    def get_queryset(self):
        queryset = super(PayrollListView, self).get_queryset()
        if self.request.user.groups.filter(name='Nanny').exists():
            queryset = queryset.filter(employee=self.request.user.profile)\
                .annotate(
                employer_taxes=F('employer_social_security') + F('employer_medicare') + F('futa') + F('wa_uta'),)\
                .prefetch_related('employee__user')
        else:
            queryset = queryset.annotate(
                employer_taxes=F('employer_social_security') + F('employer_medicare') + F('futa') + F('wa_uta'),)\
                .prefetch_related('employee__user')
        return queryset


class PayrollDetailView(views.LoginRequiredMixin,
                        views.MultiplePermissionsRequiredMixin,
                        DetailView):
    permissions = {
        'any': ('payroll.add_payroll', 'payroll.approve_payroll')
    }
    model = Payroll
    template_name = 'payroll/payroll_detail.html'

    def get_object(self):
        # Ensures that only those on the invoice and approvers can see invoices.
        object = get_object_or_404(Payroll, pk=self.kwargs['pk'])
        if self.request.user.profile == object.employee or self.request.user.has_perm('payroll.approve_payroll'):
            return object
        else:
            raise Http404('You are not authorized to view this invoice.')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['employee_taxes'] = self.object.employee_medicare + self.object.employee_social_security
        context['employer_taxes'] =  self.object.employer_medicare + \
                                     self.object.employer_social_security + self.object.futa + self.object.wa_uta
        context['combined_taxes'] = context['employee_taxes'] + context['employer_taxes']
        context['total_cost'] = self.object.gross_total + context['employer_taxes']
        context['net_pay'] = self.object.gross_total - context['employee_taxes']
        context['ytd'] = Payroll.objects\
            .filter(employee=self.object.employee, pay_period_end__year=self.object.pay_period_end.year)\
            .exclude(pay_period_start__gt=self.object.pay_period_start)\
            .aggregate(gross_total=Sum('gross_total'),employer_medicare=Sum('employer_medicare'),
                       employer_social_security=Sum('employer_social_security'), futa=Sum('futa'), wa_uta=Sum('wa_uta'),
                       employee_medicare=Sum('employee_medicare'), employee_social_security=Sum('employee_social_security'),
                       )
        context['ytd']['employer_taxes'] = \
            context['ytd']['employer_medicare'] + context['ytd']['employer_social_security'] + context['ytd']['futa'] + context['ytd']['wa_uta']
        context['ytd']['employee_taxes'] = context['ytd']['employee_medicare'] + context['ytd']['employee_social_security']
        context['ytd']['net_pay'] = context['ytd']['gross_total'] - context['ytd']['employee_taxes']
        context['ytd']['total_cost'] = context['ytd']['gross_total'] + context['ytd']['employer_taxes']
        context['ytd']['combined_taxes'] = context['ytd']['employer_taxes'] + context['ytd']['employee_taxes']
        return context


class PayrollEntryView(views.LoginRequiredMixin,
                       views.MultiplePermissionsRequiredMixin,
                       CreateView):
    permissions = {
        'any': ('payroll.add_payroll', 'payroll.approve_payroll')
    }
    model = Payroll
    form_class = PayrollEntryForm
    template_name = 'payroll/payroll_entry.html'

    def get_success_url(self):
        return reverse_lazy('payroll:list')

    def get_form_kwargs(self):
        kwargs = super(PayrollEntryView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def post(self, request, *args, **kwargs):
        if 'cancel' in request.POST:
            return HttpResponseRedirect(reverse_lazy('payroll:list'))
        else:
            return super(PayrollEntryView, self).post(self, request, *args, **kwargs)

    def send_email(self, obj):
        subject = '[Sébastien] Time Card Submitted'
        from_email = settings.DEFAULT_FROM_EMAIL
        context = {
            'employee': obj.employee.user.first_name,
            'pay_period_end': obj.pay_period_end,
            'id': obj.pk,
            'site_url': self.request.META['HTTP_HOST']
        }
        payroll_email_employer = render_to_string('payroll/payroll_entered_for_employer.html', context)
        approver_emails = [a.email for a in User.objects.all() if a.has_perm('payroll.approve_payroll')]
        if obj.employee.user.email:
            payroll_email_employee = render_to_string('payroll/payroll_entered_for_employee.html', context)
            send_mail(
                subject,
                'Your timecard for pay period ending {0} has been submitted for review.'.format(context['pay_period_end']),
                from_email,
                [obj.employee.user.email, ],
                fail_silently=True,
                html_message=payroll_email_employee,
            )
        send_mail(subject,
                  '{0} has entered a timecard for pay period ending {1}. Please go to sebastien.site to review and approve it.'.format(context['employee'], context['pay_period_end']),
                  from_email,
                  approver_emails,
                  fail_silently=True,
                  html_message=payroll_email_employer)

    def form_valid(self, form):
        obj = form.save(commit=False)
        try:
            if obj.employee:
                obj = form.save()
                self.send_email(obj)
                return super(PayrollEntryView, self).form_valid(form)
        except ObjectDoesNotExist:
            employee = self.request.user
            if not employee.profile.wage:
                messages.add_message(self.request, messages.ERROR,
                                     'Your account is not set up to enter time cards. Please contact an administrator.')
                return HttpResponseRedirect(reverse_lazy('payroll:list'))
            else:
                obj.employee = employee.profile
                obj.save()
                self.send_email(obj)
                return super(PayrollEntryView, self).form_valid(form)


class PayrollReviewView(views.LoginRequiredMixin,
                        views.PermissionRequiredMixin,
                        UpdateView):
    permission_required = 'payroll.approve_payroll'
    model = Payroll
    form_class = PayrollReviewForm
    template_name = 'payroll/payroll_review.html'

    def get_success_url(self):
        return reverse_lazy('payroll:list')

    def post(self, request, *args, **kwargs):
        if 'cancel' in request.POST:
            return HttpResponseRedirect(reverse_lazy('payroll:list'))
        else:
            return super(PayrollReviewView, self).post(self, request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['employee_taxes'] = self.object.employee_medicare + self.object.employee_social_security
        context['employer_taxes'] = self.object.employer_medicare + self.object.employer_social_security + self.object.futa + self.object.wa_uta
        context['combined_taxes'] = context['employee_taxes'] + context['employer_taxes']
        context['total_cost'] = self.object.gross_total + context['employer_taxes']
        context['net_pay'] = self.object.gross_total - context['employee_taxes']
        context['ytd'] = Payroll.objects\
            .filter(employee=self.object.employee, pay_period_end__year=self.object.pay_period_end.year)\
            .exclude(pay_period_start__gt=self.object.pay_period_start)\
            .aggregate(gross_total=Sum('gross_total'), employer_medicare=Sum('employer_medicare'),
                       employer_social_security=Sum('employer_social_security'), futa=Sum('futa'), wa_uta=Sum('wa_uta'),
                       employee_medicare=Sum('employee_medicare'),
                       employee_social_security=Sum('employee_social_security'),
                       )
        context['ytd']['employer_taxes'] = \
            context['ytd']['employer_medicare'] + context['ytd']['employer_social_security'] + context['ytd']['futa'] + context['ytd']['wa_uta']
        context['ytd']['employee_taxes'] = context['ytd']['employee_medicare'] + context['ytd']['employee_social_security']
        context['ytd']['net_pay'] = context['ytd']['gross_total'] - context['ytd']['employee_taxes']
        context['ytd']['total_cost'] = context['ytd']['gross_total'] + context['ytd']['employer_taxes']
        context['ytd']['combined_taxes'] = context['ytd']['employer_taxes'] + context['ytd']['employee_taxes']
        return context

    def send_email(self, obj):
        subject = '[Sébastien] Time Card Approved'

payroll/templates/payroll/details_for_payroll.html
<div class="row">

    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h5 class="text-center">Employer Taxes</h5>
            </div>
            <div class="card-body">
                <table class="table">
                <thead>
                    <tr>
                        <th></th>
                        <th class="text-center">Pay Period</th>
                        <th class="text-center">Year to Date</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="text-center">Wages</td>
                        <td class="text-center">${{ object.gross_total }}</td>
                        <td class="text-center">${{ ytd.gross_total }}</td>
                    </tr>
                    <tr>
                        <td class="text-center">Medicare</td>
                        <td class="text-center"><i>${{ object.employer_medicare }}</i></td>
                        <td class="text-center"><i>${{ ytd.employer_medicare }}</i></td>
                    </tr>
                    <tr>
                        <td class="text-center">Social Security</td>
                        <td class="text-center"><i>${{ object.employer_social_security }}</i></td>
                        <td class="text-center"><i>${{ ytd.employer_social_security }}</i></td>
                    </tr>
                    <tr>
                        <td class="text-center">FUTA</td>
                        <td class="text-center"><i>${{ object.futa }}</i></td>
                        <td class="text-center"><i>${{ ytd.futa }}</i></td>
                    </tr>
                    <tr>
                        <td class="text-center">WASUTA</td>
                        <td class="text-center"><i>${{ object.wa_uta }}</i></td>
                        <td class="text-center"><i>${{ ytd.wa_uta }}</i></td>
                    </tr>
                    <tr>
                        <td class="text-center"><i>Subtotal</i></td>
                        <td class="text-center"><i>${{ employer_taxes }}</i></td>
                        <td class="text-center"><i>${{ ytd.employer_taxes }}</i></td>
                    </tr>
                    <tr>
                        <td class="text-center"><b>Total Cost</b></td>
                        <td class="text-center"><i>${{ total_cost }}</i></td>
                        <td class="text-center"><i>${{ ytd.total_cost }}</i></td>
                    </tr>
                </tbody>
            </table>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h5 class="text-center">Employee Taxes</h5>
            </div>
            <div class="card-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th></th>
                            <th class="text-center">Pay Period</th>
                            <th class="text-center">Year to Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="text-center">Wages</td>
                            <td class="text-center">${{ object.gross_total }}</td>
                            <td class="text-center">${{ ytd.gross_total }}</td>
                        </tr>
                        <tr>
                            <td class="text-center">Medicare</td>
                            <td class="text-center"><i>${{ object.employee_medicare }}</i></td>
                            <td class="text-center"><i>${{ ytd.employee_medicare }}</i></td>
                        </tr>
                        <tr>
                            <td class="text-center">Social Security</td>
                            <td class="text-center"><i>${{ object.employee_social_security }}</i></td>
                            <td class="text-center"><i>${{ ytd.employee_social_security }}</i></td>
                        </tr>
                        <tr>
                            <td class="text-center"><i>Subtotal</i></td>
                            <td class="text-center"><i>${{ employee_taxes }}</i></td>
                            <td class="text-center"><i>${{ ytd.employee_taxes }}</i></td>
                        </tr>
                        <tr>
                            <td class="text-center"><b>Net Pay</b></td>
                            <td class="text-center"><i>${{ net_pay }}</i></td>
                            <td class="text-center"><i>${{ ytd.net_pay }}</i></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <br/>
        <div class="card">
            <div class="card-header">
                <h5 class="text-center">Combined Taxes</h5>
            </div>
            <div class="card-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th></th>
                            <th class="text-center">Pay Period</th>
                            <th class="text-center">Year to Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="text-center"><i>Total</i></td>
                            <td class="text-center"><i>${{ combined_taxes }}</i></td>
                            <td class="text-center"><i>${{ ytd.combined_taxes }}</i></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

payroll/templates/payroll/employee_form.html
{% include '__base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <br>
    <div class="col-md-5 offset-3">
        <div class="card">
            <div class="card-header">
                <h4>Enter Employee Information</h4>
            </div>
            <div class="card-body">
                    {% crispy form %}
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        $(document).ready(function(){
            $('.dateinput').datepicker({
                autoclose: true,
                assumeNearbyYear:true
            });
        })
    </script>
{% endblock %}

payroll/templates/payroll/payroll_approved_for_employee.html
Hello {{ employee }},<br/>
<br/>
Your time card for pay period ending {{ pay_period_end }} has been approved.<br/>
<br/>
<a href="{{ site_url }}{% url 'payroll:detail' id %}">You can view the invoice here.</a>

payroll/templates/payroll/payroll_approved_for_employer.html
Hello Approver,<br/>
<br/>
The time card for {{ first_name }} with pay period ending {{ pay_period_end }} has been approved.<br/>
<br/>
<a href="{{ site_url }}{% url 'payroll:detail' id %}">You can view the invoice here.</a>

payroll/templates/payroll/payroll_detail.html
{% extends '__base.html' %}
{% block css %}
    {{ block.super }}
    <style>
        .borderless td, .borderless th {
            border: none;
        }
    </style>
{% endblock %}
{% block navbar %}
{% endblock %}

{% block center_bar %}
    <div class="card">
        <div class="card-header text-center">
            <div class="d-flex justify-content-between">
                <div class="col-md-4 text-left">
                    Federal Tax ID: {% include 'payroll/redacted/federal_tax.html' %}<br/>
                    Washington Tax ID: {% include 'payroll/redacted/state_tax.html' %}<br/>
                </div>
                <div class="col-md-4">
                    <h2>Invoice #{{ object.id }}</h2>
                </div>
                <div class="col-md-4">
                    <u>Date of Payment:</u><br/>
                    {% if object.date_paid %}
                        {{ object.date_paid }}
                    {% else %}
                        <div style="color: red">Not Paid Yet</div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-3">
                    <u>Paid By:</u><br/>
                    {% include 'payroll/redacted/address.html' %}
                </div>
                <div class="col-md-3">
                    <u>Paid To:</u><br/>
                    {{ object.employee.user.first_name }} {{ object.employee.user.last_name }}<br/><br/>
                    <u>For:</u><br/>
                    {% include 'payroll/redacted/purpose.html' %}
                </div>
                <div class="col-md-3">
                    <table class="table table-sm borderless">
                        <tr>
                            <td colspan="2"><u>Dates of Service:</u></td>
                        </tr>
                        <tr>
                            <td colspan="2">{{ object.pay_period_start }} - {{ object.pay_period_end }}</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><u>Hours</u></td>
                            <td><u>Wage</u></td>
                        </tr>
                        <tr>
                            <td>{{ object.hours }}</td>
                            <td>{{ object.current_wage }}</td>
                        </tr>
                    </table>

                </div>
                <div class="col-md-3">
                    <u>Invoice Total:</u><br/>
                    <h2 style="color:blue">${{ object.gross_total }}</h2>
                </div>
            </div>
            <hr>
    {% include 'payroll/details_for_payroll.html' %}

        </div>
    </div>
{% endblock %}

payroll/templates/payroll/payroll_entered_for_employee.html
Hello {{ employee }},<br/>
<br/>
Your time card with pay period ending {{ pay_period_end }} has been submitted and is awaiting approval.<br/>
<br/>
<a href="{{ site_url }}{% url 'payroll:detail' id %}">You can view the invoice here.</a>

payroll/templates/payroll/payroll_entered_for_employer.html
Hello Approvers,<br/>
<br/>
{{ employee }} has entered a time card for pay period ending {{ pay_period_end }}.<br/>
<br/>
<a href="{{ site_url }}{% url 'payroll:review' id %}">You can review and approve the timecard here.</a>

payroll/templates/payroll/payroll_entry.html
{% extends '__base.html' %}
{% load crispy_forms_tags %}

{% block center_bar %}
        <div class="card">
            <div class="card-header">
                <h4>Enter Time Card</h4>
            </div>
            <div class="card-body">
                {% crispy form %}
            </div>

        </div>
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script>
        $(document).ready(function(){
            $('.dateinput').datepicker({
                orientation:'bottom left',
                autoclose: true,
                assumeNearbyYear:true
            });
        })
    </script>
{% endblock %}

payroll/templates/payroll/payroll_list.html
{% extends '__base.html' %}
{% load mathfilters %}
{% load profile_extras %}

{% block center_bar %}
    <div class="card">
        <div class="card-header text-center">
            <h3>Payroll</h3>
        </div>
        <div class="card-body">
            {% for obj in object_list %}
                <ul class="list-group">
                    <li class="list-group-item">
                    <div class="btn-group float-right" role="group">
                            <a href="{% url 'payroll:detail' obj.id %}" class="btn btn-primary float-right">Invoice</a>
                        {% if not obj.paid %}
                            {% if perms.payroll.approve_payroll %}
                                <a href="{% url 'payroll:review' obj.pk %}" class="btn btn-warning float-right">Approve</a>
                            {% else %}
                                <button class="btn btn-outline-success disabled float-right">Submitted</button>
                            {% endif %}
                        {% endif %}
                        {% if obj.paid %}
                            <a href="{% url 'payroll:detail' obj.id %}" class="btn btn-success float-right">Approved</a>
                        {% endif %}
                    </div>
                        {% if perms.payroll.approve_payroll %}<u>{{ obj.employee.user.first_name }} {{ obj.employee.user.last_name }}</u> - {{ obj.hours }} hours<br/>{% endif %}
                        {{ obj }}{% if not perms.payroll.approve_payroll %} - {{ obj.hours }} hours{% endif %}<br/>
                        Pay: ${{ obj.gross_total }}; Employer Taxes: ${{ obj.employer_taxes }}; Total Cost: ${{ obj.gross_total|addition:obj.employer_taxes }}

                    </li>
                </ul>
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block right_sidebar %}
    {% if perms.payroll.add_payroll %}
        <a role="button" class="btn btn-primary" href="{% url 'payroll:entry' %}">New Payroll Entry</a>
    {% endif %}
{% endblock %}

payroll/templates/payroll/payroll_review.html
{% extends '__base.html' %}
{% load crispy_forms_tags %}

{% block center_bar%}
    <div class="card">
        <div class="card-header">
            <h4>Approve Time Card</h4>
        </div>
        <div class="card-body">
            {% crispy form %}
        </div>
    </div>

    <br>
{% include 'payroll/details_for_payroll.html' %}

{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script>
        $(document).ready(function(){
            $('.dateinput').datepicker({
                format: 'yyyy-mm-dd',
                orientation:'bottom left',
                autoclose: true,
                assumeNearbyYear:true
            });
        })
    </script>
{% endblock %}